### ISSUE TITLE
checklist for V1 on CRAN

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/sunburstR#46]
- [x] increment version in DESCRIPTION
- [x] update NEWS.md
- [x] run CRAN checks locally and with travis, win-builder, and rhub
- [x] submit to CRAN
